# Configuration file for Travis CI test environment
language: php
php: [5.3]

before_script:
  - composer install --prefer-dist
  - vendor/bin/koharness

# Run the PDFview tests
script: cd /tmp/koharness && vendor/bin/phpunit --bootstrap=vendor/kohana/unittest/bootstrap.php --group=pdfview vendor/kohana/unittest/tests.php
