# Configuration file for Travis CI test environment
language: php
php:
  - 5.3
  - 5.2

env:
  - KO_SANDBOX=/home/vagrant/kohana
  
before_script:
  # Create a kohana environment
  - php ./dev/ko_sandbox.php

# Run the PDFview tests
script: phpunit --bootstrap=$KO_SANDBOX/modules/unittest/bootstrap.php --group=pdfview $KO_SANDBOX/modules/unittest/tests.php